### ISSUE TITLE
xGroup with MembersToInclude throws error "The specified account name is already a member of the group."

### ISSUE THREAD

**Issue by r14git** [PowerShell/xPSDesiredStateConfiguration#54] opened 2015-12-14 19:03 UTC
```
    xGroup AddToAdmin {
        GroupName='Administrators'
        DependsOn= '[User]LocalAdmin'
        Ensure= 'Present'
        MembersToInclude=$Node.LocalUserName
        Credential = $domainCred
    }
```

When I run script for the first time user is added to local administrators group properly.
When I run script for the second time I got error:

VERBOSE: [TEST1A]: LCM:  [ Start  Resource ]  [[User]LocalAdmin]
VERBOSE: [TEST1A]: LCM:  [ Start  Test     ]  [[User]LocalAdmin]
VERBOSE: [TEST1A]:                            [[User]LocalAdmin] A user with the name Admin2 exists.
VERBOSE: [TEST1A]:                            [[User]LocalAdmin] The value of the Password property does not match.
VERBOSE: [TEST1A]: LCM:  [ End    Test     ]  [[User]LocalAdmin]  in 4.9530 seconds.
VERBOSE: [TEST1A]: LCM:  [ Start  Set      ]  [[User]LocalAdmin]
VERBOSE: [TEST1A]:                            [[User]LocalAdmin] Configuration of user Admin2 started.
VERBOSE: [TEST1A]:                            [[User]LocalAdmin] Performing the operation "Set" on target "User: Admin2".
VERBOSE: [TEST1A]:                            [[User]LocalAdmin] User Admin2 properties updated successfully.
VERBOSE: [TEST1A]:                            [[User]LocalAdmin] Configuration of user Admin2 completed successfully.
VERBOSE: [TEST1A]: LCM:  [ End    Set      ]  [[User]LocalAdmin]  in 0.3910 seconds.
VERBOSE: [TEST1A]: LCM:  [ End    Resource ]  [[User]LocalAdmin]
VERBOSE: [TEST1A]: LCM:  [ Start  Resource ]  [[xGroup]AddToAdmin]
VERBOSE: [TEST1A]: LCM:  [ Start  Test     ]  [[xGroup]AddToAdmin]
VERBOSE: [TEST1A]:                            [[xGroup]AddToAdmin] A group with the name Administrators exists.
VERBOSE: [TEST1A]:                            [[xGroup]AddToAdmin] Resolving admin2 as a local account.
VERBOSE: [TEST1A]:                            [[xGroup]AddToAdmin] Resolving admin2 as a user.
VERBOSE: [TEST1A]:                            [[xGroup]AddToAdmin] At least one member Admin2 of the provided MembersToInclude parameter does not have a match in the existing group Administrators.
VERBOSE: [TEST1A]: LCM:  [ End    Test     ]  [[xGroup]AddToAdmin]  in 0.6400 seconds.
VERBOSE: [TEST1A]: LCM:  [ Start  Set      ]  [[xGroup]AddToAdmin]
VERBOSE: [TEST1A]:                            [[xGroup]AddToAdmin] Performing the operation "Set" on target "Group: Administrators".
VERBOSE: [TEST1A]:                            [[xGroup]AddToAdmin] Resolving admin2 as a local account.
VERBOSE: [TEST1A]:                            [[xGroup]AddToAdmin] Resolving admin2 as a user.
Exception calling "Save" with "0" argument(s): "The specified account name is already a member of the group.
"
    + CategoryInfo          : NotSpecified: (:) [], CimException
    + FullyQualifiedErrorId : PrincipalOperationException
    + PSComputerName        : localhost

VERBOSE: [TEST1A]: LCM:  [ End    Set      ]  [[xGroup]AddToAdmin]  in 0.3290 seconds.
The PowerShell DSC resource MSFT_xGroupResource threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for mo
re details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost

**Comment by jonathaneckman** [comment] 2017-11-16 21:13
Is there a workaround?

**Comment by johlju** [comment] 2018-05-11 13:52
Does anyone have a example to reproduce this? How does the configuration look like and how does the current state look like before the configuration is run?
If we have that then someone in the community could write tests for this so we could get this solved.

**Comment by mhendric** [comment] 2019-02-17 23:46
I cannot reproduce this one. Sounds like we either still need valid repro steps, or this has been fixed in either a newer version of PowerShell or this module. I'm going to close this with a 'needs more information' tag. If someone comes up with more details feel free to re-open.

Windows 10 (1809) / PS 5.1
Created local group TestGroup1
Created local user TestUser1
Ran the following config twice:

```
Configuration xGroup_SetMembersConfig
{
    Import-DscResource -ModuleName 'xPSDesiredStateConfiguration'

    Node localhost
    {
        xGroup AddToAdmin {
            GroupName='TestGroup1'
            Ensure= 'Present'
            MembersToInclude='TestUser1'
        }
    }
}
```

Results:
```
PS C:\users\Mike\Desktop> Start-DscConfiguration -Path .\xGroup_SetMembersConfig -Verbose -Wait -Force
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManag
er,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer MIKEHDELL1 with user sid S-1-5-21-2925749877-2109271732-1678962896-1001.
VERBOSE: [MIKEHDELL1]: LCM:  [ Start  Set      ]
VERBOSE: [MIKEHDELL1]: LCM:  [ Start  Resource ]  [[xGroup]AddToAdmin]
VERBOSE: [MIKEHDELL1]: LCM:  [ Start  Test     ]  [[xGroup]AddToAdmin]
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] Invoking the function Test-TargetResourceOnFullSKU for the group TestGroup1.
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] A group with the name TestGroup1 exists.
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] Resolving TestUser1 as a local account.
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] MembersToExclude is empty. No group member removals are needed.
VERBOSE: [MIKEHDELL1]: LCM:  [ End    Test     ]  [[xGroup]AddToAdmin]  in 2.6870 seconds.
VERBOSE: [MIKEHDELL1]: LCM:  [ Start  Set      ]  [[xGroup]AddToAdmin]
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] Begin executing Set functionality on the group TestGroup1.
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] Performing the operation "Set" on target "Group: TestGroup1".
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] Resolving TestUser1 as a local account.
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] MembersToExclude is empty. No group member removals are needed.
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] Group TestGroup1 properties updated successfully.
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] End executing Set functionality on the group TestGroup1.
VERBOSE: [MIKEHDELL1]: LCM:  [ End    Set      ]  [[xGroup]AddToAdmin]  in 2.7500 seconds.
VERBOSE: [MIKEHDELL1]: LCM:  [ End    Resource ]  [[xGroup]AddToAdmin]
VERBOSE: [MIKEHDELL1]: LCM:  [ End    Set      ]
VERBOSE: [MIKEHDELL1]: LCM:  [ End    Set      ]    in  13.2030 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 13.335 seconds

PS C:\users\Mike\Desktop> Start-DscConfiguration -Path .\xGroup_SetMembersConfig -Verbose -Wait -Force
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManag
er,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer MIKEHDELL1 with user sid S-1-5-21-2925749877-2109271732-1678962896-1001.
VERBOSE: [MIKEHDELL1]: LCM:  [ Start  Set      ]
VERBOSE: [MIKEHDELL1]: LCM:  [ Start  Resource ]  [[xGroup]AddToAdmin]
VERBOSE: [MIKEHDELL1]: LCM:  [ Start  Test     ]  [[xGroup]AddToAdmin]
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] Invoking the function Test-TargetResourceOnFullSKU for the group TestGroup1.
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] A group with the name TestGroup1 exists.
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] Resolving TestUser1 as a local account.
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] Resolving TestUser1 as a local account.
VERBOSE: [MIKEHDELL1]:                            [[xGroup]AddToAdmin] MembersToExclude is empty. No group member removals are needed.
VERBOSE: [MIKEHDELL1]: LCM:  [ End    Test     ]  [[xGroup]AddToAdmin]  in 2.5540 seconds.
VERBOSE: [MIKEHDELL1]: LCM:  [ Skip   Set      ]  [[xGroup]AddToAdmin]
VERBOSE: [MIKEHDELL1]: LCM:  [ End    Resource ]  [[xGroup]AddToAdmin]
VERBOSE: [MIKEHDELL1]: LCM:  [ End    Set      ]
VERBOSE: [MIKEHDELL1]: LCM:  [ End    Set      ]    in  4.2420 seconds.
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 4.342 seconds

PS C:\users\Mike\Desktop> 
```

**Closed by mhendric** 2019-02-17 23:46 UTC
Labels: needs more information
