### ISSUE TITLE
dot in registry key

### ISSUE THREAD

**Issue by shurick81** [PowerShell/xPSDesiredStateConfiguration#363] opened 2017-08-06 12:51 UTC
I am trying to apply following resource:

```
        Registry LocalZone
        {
            Ensure                  = "Present"
            Key                     = "HKLM:\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\Domains\lab4.local\sp2016entdev"
            ValueName               = "HTTP"
            ValueType               = "DWORD"
            ValueData               = "1"
            PsDscRunAsCredential    = $SPInstallAccountCredential
        }

```

Here is how it looks in mof file:

```
instance of MSFT_RegistryResource as $MSFT_RegistryResource3ref
{
ResourceID = "[Registry]LocalZone";
 ValueName = "HTTP";
 PsDscRunAsCredential = $MSFT_Credential16ref;
 Key = "HKLM:\\Software\\Microsoft\\Windows\\CurrentVersion\\Internet Settings\\ZoneMap\\Domains\\lab4.local\\sp2016entdev";
 Ensure = "Present";
 SourceInfo = "D:\\Alex\\GitHub\\SharePoint-Developer-Environment\\AzureMachines\\SP2016EntDevEnv.ps1::345::9::Registry";
 ValueType = "Dword";
 ModuleName = "PSDesiredStateConfiguration";
 ValueData = {
    "1"
};

```

What I get in result after configuration is deployed is this:

![image](https://user-images.githubusercontent.com/11289124/29003383-b95cc4da-7abe-11e7-80b9-21c4425cfce4.png)

lab4sp5 is the machine that I apply this configuration to.

**Comment by mkht** [comment] 2017-08-07 15:12
I can't reproduce.

The script that I tried is below.
```PowerShell
Configuration TestConfig
{
    Import-DscResource -ModuleName xPsDesiredStateConfiguration

    xRegistry LocalZone {
        Ensure    = "Present"
        Key       = "HKLM:\Software\Microsoft\Windows\CurrentVersion\Internet Settings\ZoneMap\Domains\lab4.local\sp2016entdev"
        ValueName = "HTTP"
        ValueType = "DWORD"
        ValueData = "1"
    }
}

TestConfig -OutputPath C:\
Start-DscConfiguration -Path C:\ -Wait -Force -Verbose
```

The result is expected one.
![issue363](https://user-images.githubusercontent.com/25482642/29032802-d24c944c-7bcd-11e7-9b90-641588ee5fb1.png)

Have you tried using `xRegistry` instead of built-in `Registry` resource?
Can you provide me the output of `[System.Environment]::OSVersion` and `$PSVersionTable` ?

**Comment by johlju** [comment] 2018-05-15 11:03
Closing this as answer per the previous comment. Please reopen or comment if this was closed in error.

**Closed by johlju** 2018-05-15 11:03 UTC
