### ISSUE TITLE
ReportServerWeb - Broken with ConfigurationID method

### ISSUE THREAD

**Issue by Zuldan** [PowerShell/xPSDesiredStateConfiguration#97] opened 2016-03-23 10:38 UTC
Apologies if this should be on UserVoice instead of here. I'm happy to move it if need be.

The ReportServerWeb works perfectly fine when using RegistrationKeys but breaks when using Configuration IDs.

To prove this I created Sample_RegistrationKeys.ps1 which sets up a DSC Pull Server, configures a nodes LCM and then retrieves some report data.

I then cloned Sample_RegistrationKeys.ps1 to Sample_ConfigurationIDs.ps1 and simply commented out the registration key related stuff and added a configuration ID.

Sample_RegistrationKeys.ps1 (https://gist.github.com/Zuldan/c679bae20de0c2dcf1aa)
Sample_ConfigurationIDs.ps1 (https://gist.github.com/Zuldan/c0fd292838b8d35c6383)

In Sample_RegistrationKeys.ps1 I'm able to retrieve report data
In Sample_ConfigurationIDs.ps1 I cannot retrieve report data because the node cannot submit report data (see event log below)

I think the clue may sit here https://msdn.microsoft.com/en-us/powershell/dsc/pullserver
<strong>
"The lack of the ConfigurationID property in the metaconfiguration file implicitly means that pull server is supporting the V2 version of the pull server protocol so an initial registration is required. Conversely, the presents of a ConfigurationID means that the V1 version of the pull server protocol is used and there is no registration processing."
</strong>

I'm taking that as when a ConfigurationID is used, the reporting mode is v1 and the new Report Server only works with reporting mode v2? I could be totally wrong.

This error appears in the the DSC WinEvent log on the node when Sample_ConfigurationIDs.ps1 is used.

Log Name:      Microsoft-Windows-DSC/Operational
Source:        Microsoft-Windows-DSC
Date:          3/23/2016 4:32:51 PM
Event ID:      4260
Task Category: None
Level:         Error
Keywords:      
User:          SYSTEM
Computer:      LABSERVER02
Description:
Job {AAFECED4-F0B8-11E5-80C7-005056B644A2} : 
Http Client 1d545e3b-60c3-47a0-bf65-5afc05182fd1 failed for WebReportManager for configuration The attempt to send status report to the server https://LABSERVER01:8080/PSDSCPullServer.svc/Node(ConfigurationId='1d545e3b-60c3-47a0-bf65-5afc05182fd1')/SendStatusReport returned unexpected response code BadRequest..

Notice the <strong>"BadRequest"</strong> in the event. maybe this is because the reporting server is in report mode V1?

**Comment by kamranayub** [comment] 2016-03-23 22:13
This is made worse by the fact you cannot use partial configurations with configuration names--the LCM doesn't pull configurations if you try to use partials with configuration name, you have to set `ConfigurationID` for partial configs to work.

**Comment by NarineM** [comment] 2016-03-23 22:30
@Zuldan 
Looks like you are missing a step in ConfigurationId scenario that creates configuration document mof (guid.mof)  file and its checksum and place it on the pull server, in Configuration repository as documented in https://msdn.microsoft.com/en-us/powershell/dsc/pullserver

**Comment by kamranayub** [comment] 2016-03-23 22:34
@NarineM I assume he's in the same boat as me. I have all the required MOF files and checksums, because configuration *pulls* fine. But it still can't send status report, same error as above.

**Comment by Zuldan** [comment] 2016-03-23 23:16
@Narine, thank you so much for your response.

I purposely did not create a MOF file for the node. I simple wanted to configure the nodes LCM and then get a status report from the Report Server. The samples are to show that the Report Server does not function when the Pull Server is in ConfigurationID mode. As kamranayub has said, even if you create the MOF files and the node pulls the config, the node still cannot send a report status to the Report Server. 'BadRequest' is received from the Report Server. I'm now 95% sure this is a bug.

Http Client 1d545e3b-60c3-47a0-bf65-5afc05182fd1 failed for WebReportManager for configuration The attempt to send status report to the server https://LABSERVER01:8080/PSDSCPullServer.svc/Node(ConfigurationId='1d545e3b-60c3-47a0-bf65-5afc05182fd1')/SendStatusReport <strong>returned unexpected response code BadRequest</strong>

You should easily be able to replicate the issue in a test environment.

**Comment by Zuldan** [comment] 2016-03-28 21:05
@NarineM, could you kindly confirm if this is a bug?

**Comment by NarineM** [comment] 2016-03-31 22:45
@Zuldan , @kamranayub 
If the node is setup to use ConfigurationID , ConfigurationID.mof has to present on the pull/reporting server (in the DSCService\Configuration folder).  This ID is used by reporting server to authorize the client for send report operation. If a file with the name <ConfigurationId>.mof does not present on the reporting server, the server would reject the client request to send a report. Since you do not have configurationId.mof in your environemnt you see "(ConfigurationId='1d545e3b-60c3-47a0-bf65-5afc05182fd1')/SendStatusReport returned unexpected response code BadRequest" error in the ETW event logs.

**Comment by NarineM** [comment] 2016-03-31 22:47
@Zuldan , @kamranayub 
It is similar to registrationKey scenario where the node has to be setup with a registration key and that key is required to present on the reporting server (in DSCService\RegitrationKey.txt file) . This key is used by the reporting server to authorize the client for sending status report operations.

**Comment by Zuldan** [comment] 2016-04-05 02:07
Hi Narine, thank you for your persistence with this. I feel a bit silly I can't get this working.

I updated the Sample https://gist.github.com/Zuldan/c0fd292838b8d35c6383 to include build a config for the Node Server (client) and place the mof file in C:\Program Files\WindowsPowerShell\DscService\Configuration, however the node is still unable to report to the Pull Server

Log Name:      Microsoft-Windows-DSC/Operational
Source:        Microsoft-Windows-DSC
Date:          4/5/2016 11:39:15 AM
Event ID:      4260
Task Category: None
Level:         Error
Keywords:      
User:          SYSTEM
Computer:      LABSERVER01.lab.local
Description:
Job {2AD146A6-FACF-11E5-80CA-005056B6357A} : 
Http Client 1d545e3b-60c3-47a0-bf65-5afc05182fd0 failed for WebReportManager for configuration The attempt to send status report to the server https://LABSERVER01:8080/PSDSCPullServer.svc/Node(ConfigurationId='1d545e3b-60c3-47a0-bf65-5afc05182fd0')/SendStatusReport returned unexpected response code BadRequest..

From LABSERVER01 (Pull Server)

PS C:\Users\labuser01\IisWebServer> Test-Path -Path 'C:\Program Files\WindowsPowerShell\DscService\Configuration\1d545e3b-60c3-47a0-bf65-5afc05182fd0.mof'
True

PS C:\Users\labuser01\IisWebServer> test-path -Path 'C:\Program Files\WindowsPowerShell\DscService\Configuration\1d545e3b-60c3-47a0-bf65-5afc05182fd0.mof.checksum'
True

Question 1: Is there anything else that is required for the reporting server to authorize the client for send report operation?

Question 2: You said "ConfigurationID.mof has to present on the pull/reporting". How would this work in a partial configuration setup where the filename is "MyConfigName.ConfigID.mof"? Which MOF file does it use to authorize the client?

**Comment by NarineM** [comment] 2016-04-05 20:52
Hi @Zuldan ,
Let us try the following steps to see what is wrong in your setup.
Make sure the 1d545e3b-60c3-47a0-bf65-5afc05182fd0.mof and its checksum present on the machine that is setup as a pull server under DSCService\Configuration folder. 
Run iisreset on the machine that is setup as pull endpoint. 
Since you are looking at ETW logs, can you delete all the existing ETW logs on the pull node ? 
Then run Update-DSCConfiguration -Wait -Verbose on the node that is setup to pull 1d545e3b-60c3-47a0-bf65-5afc05182fd0 configuration document and tell what is the verbose you see in the console?

**Comment by Zuldan** [comment] 2016-04-08 20:22
@NarineM, is there anything else you would like me to do?

**Comment by NarineM** [comment] 2016-04-11 17:16
Hi @Zuldan 
What OS and WMF configuration you have on the pull server and the pull node?

**Comment by Zuldan** [comment] 2016-04-11 21:07
@NarineM, for both I'm using Windows 2012 R2 Standard (Update) and WMF info is below...

Name                           Value
----                           -----
PSVersion                      5.0.10586.117
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.10586.117
CLRVersion                     4.0.30319.34014
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Comment by NarineM** [comment] 2016-04-12 00:53
@Zuldan 
Was the pull server deployed on a machine with just WMF 5 RTM? Were there any older WMFs installed? After you installed WMF 5, did you re-install the pull server endpoint? Are you using xWebService resource for deploying an endpoint? Which version of xPSDesiredStateconfiguraiton module you have?

**Comment by Zuldan** [comment] 2016-04-12 11:52
@NarineM, yes im using xWebService for deploying an endpoint. See https://gist.github.com/Zuldan/c0fd292838b8d35c6383

xPSDesiredStateConfiguration v3.7.0.0

**Comment by kamranayub** [comment] 2016-04-12 12:45
Sorry, following the thread, but wanted to chime in and mention I am using
the exact same configuration as Zuldan as well. Fresh VMs, fresh installs,
latest versions of everything.

Narine, are you able to confirm this scenario works with partial configs?
Or are you attempting to reproduce this in a lab? Have you run the sample
code provided to reproduce? Appreciate the help!

**Comment by NarineM** [comment] 2016-04-12 19:17
@kamranayub 
After I fixed Sample_ConfigurationIDs.ps1  to deploy guid.mof and guid.mof.checksum in pull server configuration repository, I can not repro the issue. I see exact same error only when the guid.mof does not present in the pull server repository.

**Comment by kamranayub** [comment] 2016-04-12 20:15
But does the pull client still pull the partial configuration appropriately
then? The documentation makes it seem like in WMF 5 partial MOFs MUST be
named Name.Guid.mof, not just Guid.mof.

**Comment by Zuldan** [comment] 2016-04-12 21:25
@NarineM, Sample_ConfigurationIDs.ps1 (https://gist.github.com/Zuldan/c0fd292838b8d35c6383) already has code to deploy guid.mof and guid.mof.checksum (see below). Could you kindly post your version of Sample_ConfigurationIDs.ps1 so we can see what we're doing wrong?

#region Node Config
Configuration IisWebServer
{
    Node $ConfigID
    {
        WindowsFeature IIS
        {
            Ensure="Present"
            Name="Web-Server"
        }
    }
}

IisWebServer -OutputPath 'C:\Program Files\WindowsPowerShell\DscService\Configuration'
New-DSCChecksum -ConfigurationPath 'C:\Program Files\WindowsPowerShell\DscService\Configuration' -OutPath 'C:\Program Files\WindowsPowerShell\DscService\Configuration' -Verbose -Force
Update-DscConfiguration -ComputerName $NodeServer -wait -verbose
#endregion

**Comment by NarineM** [comment] 2016-04-12 21:42
Here is the part that needs to be changed:
 $requestUri = "$serviceURL/Nodes(ConfigurationId= '$ConfigurationId')/Reports" 
 $request = Invoke-WebRequest -Uri $requestUri  -ContentType "application/json;odata=minimalmetadata;streaming=true;charset=utf-8" ` 
               -UseBasicParsing -Headers @{Accept = "application/json";ProtocolVersion = "2.0"} ` 
             -ErrorAction SilentlyContinue -ErrorVariable ev 

Needs to be changed to:
 $requestUri = "$serviceURL/Node(ConfigurationId= '$ConfigurationId')/StatusReports" 
     $request = Invoke-WebRequest -Uri $requestUri  -ContentType "application/json;odata=minimalmetadata;streaming=true;charset=utf-8" ` 
            -UseBasicParsing -Headers @{Accept = "application/json";ProtocolVersion = "2.0"} ` 
                -ErrorAction SilentlyContinue -ErrorVariable ev

**Comment by Zuldan** [comment] 2016-04-13 10:54
@NarineM, we are having a win! I can now report on the node thanks to your code change. I've updated the Sample https://gist.github.com/Zuldan/c0fd292838b8d35c6383

<b>Question 1:</b>How do I tell if the node is consistent/compliant?

<code>
JobId                : 574ab0d4-0163-11e6-80cb-005056b6357a
OperationType        : Consistency
ReportFormatVersion  : 2.0
ConfigurationVersion : 
StartTime            : 04/13/2016 20:34:46
EndTime              : 12/30/1899 00:00:00
Errors               : {}
StatusData           : {{"IPV4Addresses":["192.168.2.91","127.0.0.1"],"CurrentChecksum":"67D79F2FFAAC8814DBD64F2A946D4FAFBBA58BC99F87117024E1F64543BC760A","MACAddresses":["00-50-56-E6-35-7B"
                       ,"00-00-00-00-00-00-00-E0"],"Type":"Consistency","HostName":"S12AUMDC01TST19","Locale":"en-US","StartDate":"2016-04-13T20:34:46.9590000+10:00","JobID":"{574AB0D4-0163-1
                       1E6-80CB-005056B6357A}","LCMVersion":"2.0","IPV6Addresses":["fe80::3caf:eb8e:790f:28e2%12","::2000:0:0:0","::1","::2000:0:0:0"]}}

IPV4Addresses   : {192.168.2.91, 127.0.0.1}
CurrentChecksum : 67D79F2FFAAC8814DBD64F2A946D4FAFBBA58BC99F87117024E1F64543BC760A
MACAddresses    : {00-50-56-E6-35-7B, 00-00-00-00-00-00-00-E0}
Type            : Consistency
HostName        : LABSERVER02
Locale          : en-US
StartDate       : 2016-04-13T20:34:46.9590000+10:00
JobID           : {574AB0D4-0163-11E6-80CB-005056B6357A}
LCMVersion      : 2.0
IPV6Addresses   : {fe80::3caf:eb8e:790f:28e2%12, ::2000:0:0:0, ::1, ::2000:0:0:0}
</code>

<b>Question 2:</b> I've rebuilt the pullserver and node from scratch but I'm still receiving this error on the node and so are other people. Is this a bug?

<code>Job {5253B19B-0161-11E6-80CB-005056B6357A} : 
Http Client 1d545e3b-60c3-47a0-bf65-5afc05182fd0 failed for WebReportManager for configuration The attempt to send status report to the server https://LABSERVER01:8080/PSDSCPullServer.svc/Node(ConfigurationId='1d545e3b-60c3-47a0-bf65-5afc05182fd0')/SendStatusReport returned unexpected response code BadRequest..</code>

**Comment by NarineM** [comment] 2016-04-13 18:52
@Zuldan,
If the consistency failed to apply the configuration you will see the errors in Errors field. That will tell that the node is not compliant.  Reporting using ConfigurationID in WMF 5 has limited StatusData content. When you switch to use registrationKey, reporting data contains additional fields such as the overall status of the operation in "Status" property, also populates detailed information about which resources are in desired state,which onces are not in desired state and the resource level errors if a particular resource instance failed.

**Comment by NarineM** [comment] 2016-04-13 18:57
@Zuldan 
For your question #2. I do not think there should be an error about the node not being able to send reports to the reporting server when it actually does.
If your question is about a node that is not sending any reports with that error. then these are the possible causes:
1. Given configurationId,mof does not present on the pull server configuration repository
2. client is using WMF 5, but the server is using older version (like WMF 4) where reporting was not available. So the older server rejects requests it is not able to interpret.

**Comment by gigi81** [comment] 2016-04-13 22:54
Hi @NarineM,
As specified here #106, I'm having the same issue reported by @Zuldan regarding node reporting errors.
It seems quite clear to me that this is a bug.
I can confirm that in my configuration:
1. the mof and checksum files are there
2. WMF5 is installed on both client and server

Are we sure that the dll installed by the xDscWebService resource in the web service endpoint is the correct one? Where is this dll coming from? What is the version of the dll compatible with WMF5?

**Comment by NarineM** [comment] 2016-04-14 01:10
@gigi81 
In @Zuldan 's scenario he is able to pull the node status records from the reporting server now (after changing the request URLs), but sill continues seeing BadRequest in ETW log. 
Is it similar to what you are seeing?

**Comment by gigi81** [comment] 2016-04-14 06:32
Yes, I'm having the same BadRequest error in the log.

**Comment by NarineM** [comment] 2016-04-14 18:15
@gigi81,
I will look into this ETW message and see why it is being logged when the operation is sucesful, for now you can ignore it.

**Comment by NarineM** [comment] 2016-04-14 23:30
Closing the thread since original issue with not being able to send and retrieve reports got addressed. The remaining is the ETW events with BadRequest despite the operation is successful.

**Closed by NarineM** 2016-04-14 23:30 UTC

**Comment by gigi81** [comment] 2016-04-18 13:53
Hi @NarineM,
I tried to retrieve the status report with the powershell script by @Zuldan but the response returned by the server is empty (content.value is empty to be more precise).
Here is the ouput from the command:

StatusCode        : 200
StatusDescription : OK
Content           : {"odata.metadata":"http://localhost:8050/PSDSCPullServer.svc/$metadata#StatusReport","value":[]}
RawContent        : HTTP/1.1 200 OK
                    ProtocolVersion: 2.0
                    X-Content-Type-Options: nosniff
                    request-id: 860ff380-962d-0002-1eb2-10862d96d101
                    DataServiceVersion: 3.0;
                    Content-Length: 96
                    Cache-Control: no-cache
                    Content...
Forms             : 
Headers           : {[ProtocolVersion, 2.0], [X-Content-Type-Options, nosniff], [request-id, 860ff380-962d-0002-1eb2-10862d96d101], [DataServiceVersion, 
                    3.0;]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : 
RawContentLength  : 96

And here is the data in the esent database:

![esent-statusreport](https://cloud.githubusercontent.com/assets/881067/14606441/2c43fa4c-0575-11e6-82ab-a005939bf499.png)

**Comment by jym972** [comment] 2016-04-20 07:41
Hi,
I have almost the same problem.

I'm using ConfigurationID as my nodes are not named at the beginning
[DscLocalConfigurationManager()]
Configuration PullClientV2
{
	Param (
		[Parameter(Mandatory = $True)]
		[String]$NodeGUID
	)
	$moduleversion="1.0"
	
	Settings
	{
		ActionAfterReboot = "ContinueConfiguration"
		AllowModuleOverwrite = $true
		ConfigurationID = $NodeGUID
        ConfigurationMode = "ApplyAndAutoCorrect"
        ConfigurationModeFrequencyMins = 15
		RebootNodeIfNeeded = $true
        RefreshFrequencyMins = 30
        RefreshMode = "Pull"
        StatusRetentionTimeInDays = 10
	}

	ConfigurationRepositoryWeb Configurations
	{
		ServerURL = "https://$($DscPullServer)/psdscpullserver.svc"
		#RegistrationKey = "46d089c3-c145-4ebe-8b63-0c021e1ac04b"
    
	}
	ResourceRepositoryWeb Resources
	{
		ServerURL = "https://$($DscPullServer)/psdscpullserver.svc"
		#RegistrationKey = "46d089c3-c145-4ebe-8b63-0c021e1ac04b"
	}
	ReportServerWeb Reports
	{
		ServerURL = "https://$($DscPullServer)/psdscpullserver.svc"
		#RegistrationKey = "46d089c3-c145-4ebe-8b63-0c021e1ac04b"
	}
}

PullClientV2 -NodeGUID $Guid -Output 'C:\DSC\PullClientV2'
Set-DscLocalConfigurationManager -ComputerName 'Localhost' -Path 'C:\DSC\PullClientV2' -Verbose -Force

When I do a local Get-DscConfigurationStatus, I get "ResourcesInDesiredState"

PS C:\Users\Administrator> Get-DscConfigurationStatus|fl


JobID                      : {806920BB-06C9-11E6-80C4-00155D013228}
HostName                   : WIN-BABJSO5643U
Error                      :
Locale                     : fr-FR
IPV4Addresses              : {10.10.11.101, 127.0.0.1}
IPV6Addresses              : {fe80::e521:4830:be5:c43f%14, ::2000:0:0:0, ::1, ::2000:0:0:0}
MACAddresses               : {00-15-5D-01-32-28, 00-00-00-00-00-00-00-E0}
LCMVersion                 : 2.0
Mode                       : Pull
NumberOfResources          : 2
MetaData                   : Author: Administrator; Name: myConfiguration01; Version: 2.0.0;
                             04/20/2016 01:58:28; GenerationHost: WIN-E89T1RDB0VN;
MetaConfiguration          : MSFT_DSCMetaConfiguration
Type                       : Consistency
Status                     : Success
StartDate                  : 20/04/2016 09:28:42
DurationInSeconds          : 0
RebootRequested            : False
ResourcesInDesiredState    : {[File]HelloWorld, [WindowsFeature]TelnetClient}
ResourcesNotInDesiredState :
PSComputerName             :

When I browse the database or use  I only have a partial StatusData

function GetReport
{
	param ($AgentId = "$($(glcm).AgentId)",
		$ConfigurationID = "$($(glcm).ConfigurationID)",
		$Uri = "https://$($DscPullServer)/psdscpullserver.svc/Node(ConfigurationId='$ConfigurationId')/StatusReports"
	)
	
	$response = Invoke-WebRequest -Uri $Uri `
								 -ContentType "application/json;odata=minimalmetadata;streaming=true;charset=utf-8" `
								 -UseBasicParsing `
								 -Headers @{ Accept = "application/json"; ProtocolVersion = "1.1" } `
								 -ErrorAction SilentlyContinue -ErrorVariable ev
	$jobs = (ConvertFrom-Json $response.content).value
	return $jobs 
}

$jobs = GetReport 

foreach ($job in $jobs)
{
	
	Write-Host "JobID: $($job.JobId) StartTime: $($job.StartTime) Type: $($job.OperationType)" -ForegroundColor Green
	[console]::ForegroundColor = 'Red'
	$job.Errors | ConvertFrom-Json
	[console]::ForegroundColor = 'White'
	$job.StatusData | ConvertFrom-Json
}

JobID: 806920bb-06c9-11e6-80c4-00155d013228 StartTime: 04/20/2016 09:28:42 Type: Consistency
IPV4Addresses   : {10.10.11.101, 127.0.0.1}
CurrentChecksum : 8F690215FA9679B4B3A8F4A3C5D7C70E9E368C5126C367A1A5C4687CF477123B
MACAddresses    : {00-15-5D-01-32-28, 00-00-00-00-00-00-00-E0}
Type            : Consistency
HostName        : WIN-BABJSO5643U
Locale          : fr-FR
StartDate       : 2016-04-20T09:28:42.7280000+02:00
JobID           : {806920BB-06C9-11E6-80C4-00155D013228}
LCMVersion      : 2.0
IPV6Addresses   : {fe80::e521:4830:be5:c43f%14, ::2000:0:0:0, ::1, ::2000:0:0:0}

JobID: fbe11054-06c9-11e6-80c4-00155d013228 StartTime: 12/30/1899 00:00:00 Type:
Locale       : Unknown
ErrorCode    : 0
ErrorMessage : Unknown
ResourceId   : DSCEngine
ErrorSource  : DSCEngine


HOW CAN WE GET ResourcesInDesiredState using CONFIGURATIONID ???

Thxs a lot
