### ISSUE TITLE
ReportServerWeb - Broken with ConfigurationID 

### ISSUE THREAD

**Issue by jym972** [PowerShell/xPSDesiredStateConfiguration#119] opened 2016-04-20 08:01 UTC
Hi,
I have almost the same problem as here: https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/97 

I'm using ConfigurationID as my nodes are not named at the beginning
[DscLocalConfigurationManager()]
Configuration PullClientV2
{
	Param (
		[Parameter(Mandatory = $True)]
		[String]$NodeGUID
	)
	$moduleversion="1.0"
	
	Settings
	{
		ActionAfterReboot = "ContinueConfiguration"
		AllowModuleOverwrite = $true
		ConfigurationID = $NodeGUID
        ConfigurationMode = "ApplyAndAutoCorrect"
        ConfigurationModeFrequencyMins = 15
		RebootNodeIfNeeded = $true
        RefreshFrequencyMins = 30
        RefreshMode = "Pull"
        StatusRetentionTimeInDays = 10
	}

	ConfigurationRepositoryWeb Configurations
	{
		ServerURL = "https://$($DscPullServer)/psdscpullserver.svc"
		#RegistrationKey = "46d089c3-c145-4ebe-8b63-0c021e1ac04b"
    
	}
	ResourceRepositoryWeb Resources
	{
		ServerURL = "https://$($DscPullServer)/psdscpullserver.svc"
		#RegistrationKey = "46d089c3-c145-4ebe-8b63-0c021e1ac04b"
	}
	ReportServerWeb Reports
	{
		ServerURL = "https://$($DscPullServer)/psdscpullserver.svc"
		#RegistrationKey = "46d089c3-c145-4ebe-8b63-0c021e1ac04b"
	}
}

PullClientV2 -NodeGUID $Guid -Output 'C:\DSC\PullClientV2'
Set-DscLocalConfigurationManager -ComputerName 'Localhost' -Path 'C:\DSC\PullClientV2' -Verbose -Force

When I do a local Get-DscConfigurationStatus, I get "ResourcesInDesiredState"

PS C:\Users\Administrator> Get-DscConfigurationStatus|fl

JobID                      : {806920BB-06C9-11E6-80C4-00155D013228}
HostName                   : WIN-BABJSO5643U
Error                      :
Locale                     : fr-FR
IPV4Addresses              : {10.10.11.101, 127.0.0.1}
IPV6Addresses              : {fe80::e521:4830:be5:c43f%14, ::2000:0:0:0, ::1, ::2000:0:0:0}
MACAddresses               : {00-15-5D-01-32-28, 00-00-00-00-00-00-00-E0}
LCMVersion                 : 2.0
Mode                       : Pull
NumberOfResources          : 2
MetaData                   : Author: Administrator; Name: myConfiguration01; Version: 2.0.0;
                             04/20/2016 01:58:28; GenerationHost: WIN-E89T1RDB0VN;
MetaConfiguration          : MSFT_DSCMetaConfiguration
Type                       : Consistency
Status                     : Success
StartDate                  : 20/04/2016 09:28:42
DurationInSeconds          : 0
RebootRequested            : False
ResourcesInDesiredState    : {[File]HelloWorld, [WindowsFeature]TelnetClient}
ResourcesNotInDesiredState :
PSComputerName             :

When I browse the database or use  I only have a partial StatusData

function GetReport
{
	param ($AgentId = "$($(glcm).AgentId)",
		$ConfigurationID = "$($(glcm).ConfigurationID)",
		$Uri = "https://$($DscPullServer)/psdscpullserver.svc/Node(ConfigurationId='$ConfigurationId')/StatusReports"
	)
	
	$response = Invoke-WebRequest -Uri $Uri `
								 -ContentType "application/json;odata=minimalmetadata;streaming=true;charset=utf-8" `
								 -UseBasicParsing `
								 -Headers @{ Accept = "application/json"; ProtocolVersion = "1.1" } `
								 -ErrorAction SilentlyContinue -ErrorVariable ev
	$jobs = (ConvertFrom-Json $response.content).value
	return $jobs 
}

$jobs = GetReport 

foreach ($job in $jobs)
{
	
	Write-Host "JobID: $($job.JobId) StartTime: $($job.StartTime) Type: $($job.OperationType)" -ForegroundColor Green
	[console]::ForegroundColor = 'Red'
	$job.Errors | ConvertFrom-Json
	[console]::ForegroundColor = 'White'
	$job.StatusData | ConvertFrom-Json
}

JobID: 806920bb-06c9-11e6-80c4-00155d013228 StartTime: 04/20/2016 09:28:42 Type: Consistency
IPV4Addresses   : {10.10.11.101, 127.0.0.1}
CurrentChecksum : 8F690215FA9679B4B3A8F4A3C5D7C70E9E368C5126C367A1A5C4687CF477123B
MACAddresses    : {00-15-5D-01-32-28, 00-00-00-00-00-00-00-E0}
Type            : Consistency
HostName        : WIN-BABJSO5643U
Locale          : fr-FR
StartDate       : 2016-04-20T09:28:42.7280000+02:00
JobID           : {806920BB-06C9-11E6-80C4-00155D013228}
LCMVersion      : 2.0
IPV6Addresses   : {fe80::e521:4830:be5:c43f%14, ::2000:0:0:0, ::1, ::2000:0:0:0}

JobID: fbe11054-06c9-11e6-80c4-00155d013228 StartTime: 12/30/1899 00:00:00 Type:
Locale       : Unknown
ErrorCode    : 0
ErrorMessage : Unknown
ResourceId   : DSCEngine
ErrorSource  : DSCEngine

DIRECT DATABASE VIEW

WIN-BABJSO5643U 98e16193-06cb-11e6-80c4-00155d013228 Consistency   20/04/2016 09:43:40 30/12/1899 00:00:00 ["{\"IPV4Addresses\":[\"10.10.11.101\",\"127.0.0.1\"],\"CurrentChecksum\":\"8F690215FA9679B4B3A8F4A3C5D7C70E9E368C5126C367A1A5C4687CF477123B\",\"MACAddresses\":[\"00-15-5D-01-32-28\",\"00-00-00-00-00-00-00-E0\"],\"Type\":\"Consistency\",\"HostName\":\"WIN-BABJSO5643U\",\"Locale\":\"fr-FR\",\"StartDate\":\"2016-04-20T09:43:40.4410000+02:00\",\"JobID\":\"{98E16193-06CB-11E6-80C4-00155D013228}\",\"LCMVersion\":\"2.0\",\"IPV6Addresses\":[\"fe80::e521:4830:be5:c43f%14\",\"::2000:0:0:0\",\"::1\",\"::2000:0:0:0\"]}"] [] False 10.10.11.101;127.0.0.1;fe80::e521:4830:be5:c43f%14;::2000:0:0:0;::1;::2000:0:0:0 1135f676-40f7-4cd0-b8e0-00155D013228 

WIN-E89T1RDB0VN cc054ecd-06cb-11e6-80bd-00155d013229 Consistency   20/04/2016 09:45:06 30/12/1899 00:00:00 ["{\"IPV4Addresses\":[\"10.10.11.100\",\"127.0.0.1\"],\"CurrentChecksum\":\"384492764C4AB70C4A5979727BBE20B1C929CAB873A6D0E83BE54E6C10C02409\",\"MACAddresses\":[\"00-15-5D-01-32-29\",\"00-00-00-00-00-00-00-E0\"],\"Type\":\"Consistency\",\"HostName\":\"WIN-E89T1RDB0VN\",\"Locale\":\"fr-FR\",\"StartDate\":\"2016-04-20T09:45:06.2560000+02:00\",\"JobID\":\"{CC054ECD-06CB-11E6-80BD-00155D013229}\",\"LCMVersion\":\"2.0\",\"IPV6Addresses\":[\"fe80::e54f:3470:a625:94cf%12\",\"::2000:0:0:0\",\"::1\",\"::2000:0:0:0\"]}"] 

WINDOWS\SYSTEM32\CONFIGURATION\CONFIGURATIONSTATUS
instance of MSFT_WebDownloadManager as $Alias00000006
{
    ResourceId = "[ConfigurationRepositoryWeb]Configurations";
    SourceInfo = "::21::1::ConfigurationRepositoryWeb";
    ServerURL = "https://DscPullServer.mydsc.local/psdscpullserver.svc";
};

instance of MSFT_WebResourceManager as $Alias00000007
{
    ResourceId = "[ResourceRepositoryWeb]Resources";
    SourceInfo = "::26::1::ResourceRepositoryWeb";
    ServerURL = "https://DscPullServer.mydsc.local/psdscpullserver.svc";
};

instance of MSFT_WebReportManager as $Alias00000008
{
    ResourceId = "[ReportServerWeb]Reports";
    SourceInfo = "::31::1::ReportServerWeb";
    ServerURL = "https://DscPullServer.mydsc.local/psdscpullserver.svc";
    RegistrationKey = "46d089c3-c145-4ebe-8b63-0c021e1ac04b";
};

instance of MSFT_DSCMetaConfiguration as $Alias00000009
{
    ConfigurationModeFrequencyMins = 15;
    RebootNodeIfNeeded = True;
    ConfigurationMode = "ApplyAndAutoCorrect";
    ActionAfterReboot = "ContinueConfiguration";
    RefreshMode = "Pull";
    ConfigurationID = "1135f676-40f7-4cd0-b8e0-00155D013229";
    RefreshFrequencyMins = 30;
    AllowModuleOverwrite = True;
    DebugMode = {"NONE"};
    LCMVersion = "2.0";
    LCMCompatibleVersions = {"1.0", "2.0"};
    LCMState = "Idle";
    LCMStateDetail = "";
    ConfigurationDownloadManagers = {$Alias00000006};
    ResourceModuleManagers = {$Alias00000007};
    ReportManagers = {$Alias00000008};
    StatusRetentionTimeInDays = 10;
    AgentId = "AB73D03B-00C9-11E6-80B9-00155D013229";
};

instance of MSFT_ResourceInDesiredState as $Alias0000000A
{
    ResourceId = "[File]HelloWorld";
    SourceInfo = "::10::9::File";
    ModuleName = "PSDesiredStateConfiguration";
    ModuleVersion = "1.1";
    ConfigurationName = "myConfiguration01";
    ResourceName = "File";
    InstanceName = "HelloWorld";
    InDesiredState = True;
    StartDate = "20160420093010.221000+120";
    DurationInSeconds = 0.0000000000000000000000000000000000000000000000000000E+000;
    RebootRequested = False;
};

instance of MSFT_ResourceInDesiredState as $Alias0000000B
{
    ResourceId = "[WindowsFeature]TelnetClient";
    SourceInfo = "::14::1::WindowsFeature";
    ModuleName = "PsDesiredStateConfiguration";
    ModuleVersion = "1.1";
    ConfigurationName = "myConfiguration01";
    ResourceName = "WindowsFeature";
    InstanceName = "TelnetClient";
    InDesiredState = True;
    StartDate = "20160420093010.221000+120";
    DurationInSeconds = 2.8100000000000003000000000000000000000000000000000000E-001;
    RebootRequested = False;
};

instance of MSFT_DSCConfigurationStatus
{
    Status = "Success";
    StartDate = "20160420093010.046000+120";
    DurationInSeconds = 0;
    RebootRequested = False;
    Type = "Consistency";
    JobID = "{B397AFCF-06C9-11E6-80BD-00155D013229}";
    MetaData = "Author: Administrator; Name: myConfiguration01; Version: 2.0.0; GenerationDate: 04/20/2016 01:58:28; GenerationHost: WIN-E89T1RDB0VN;";
    NumberOfResources = 2;
    Mode = "Pull";
    LCMVersion = "2.0";
    HostName = "WIN-E89T1RDB0VN";
    IPV4Addresses = {"10.10.11.100", "127.0.0.1"};
    IPV6Addresses = {"fe80::e54f:3470:a625:94cf%12", "::2000:0:0:0", "::1", "::2000:0:0:0"};
    MACAddresses = {"00-15-5D-01-32-29", "00-00-00-00-00-00-00-E0"};
    MetaConfiguration = $Alias00000009;
    ResourcesInDesiredState = {$Alias0000000A, $Alias0000000B};
    Locale = "fr-FR";
};

HOW CAN WE GET ResourcesInDesiredState in reports using CONFIGURATIONID ???

Thxs a lot

**Comment by ArieHein** [comment] 2016-04-20 08:50
Have you tried the way described in the online documentation ?

https://msdn.microsoft.com/en-us/powershell/dsc/reportserver

**Comment by jym972** [comment] 2016-04-20 13:40
Hi, yes, I use this documentation but with ConfigurationID, as my VMs have not yet an IP nor a Name

[DscLocalConfigurationManager()]Configuration PullClientV2 {
	Node localhost {
		Settings {
			**ConfigurationID = $NodeGUID**

and my request URI is
$Uri = "$serviceURL/Node(ConfigurationId='$ConfigurationId')/StatusReports"
rather than: $Uri = "$serviceURL/Nodes(AgentId= '$AgentId')/Reports"

**ClientConfiguration01.ps1**
Remove-DscConfigurationDocument -Stage pending
Remove-DscConfigurationDocument -Stage Current

$DscPullServer = "DscPullServer.mydsc.local"

$NICs = [System.Net.NetworkInformation.NetworkInterface]::GetAllNetworkInterfaces()
foreach ($NIC in $NICs)
{
	if (($NIC.OperationalStatus -eq 'Up') -and ($NIC.NetworkInterfaceType -eq 'Ethernet'))
	{
	    [string]$Guid = "1135f676-40f7-4cd0-b8e0-" + $NIC.GetPhysicalAddress().ToString()
		break;
	}
}
$Guid

Configuration CertDownload
{
    Import-DscResource -ModuleName xPSDesiredStateConfiguration -Name xRemoteFile;
    node localhost
    {
        xRemoteFile CertPackage
        {
            Uri = "http://$($DscPullServer):8080/174e77a9-3eb2-4741-9662-4c4a056f20eb/EncryptionCertificate.cer"
            DestinationPath = 'C:\DSC\CertDownload'
        }
    }
}

CertDownload -Output 'C:\DSC\CertDownload'
Start-DscConfiguration -Wait -Force -Verbose -Path 'C:\DSC\CertDownload'

Import-Certificate -FilePath C:\DSC\CertDownload\EncryptionCertificate.cer -CertStoreLocation "CERT:\LocalMachine\ROOT" -Confirm:$false

[DscLocalConfigurationManager()]
Configuration PullClientV2
{
	Param (
		[Parameter(Mandatory = $True)]
		[String]$NodeGUID
	)
	Node localhost
	{
		Settings
		{
			ActionAfterReboot = "ContinueConfiguration"
			AllowModuleOverwrite = $true
			ConfigurationID = $NodeGUID
			ConfigurationMode = "ApplyAndAutoCorrect"
			ConfigurationModeFrequencyMins = 15
			RebootNodeIfNeeded = $true
			RefreshFrequencyMins = 30
			RefreshMode = "Pull"
			StatusRetentionTimeInDays = 10
		}
		
		ConfigurationRepositoryWeb Configurations
		{
			ServerURL = "https://$($DscPullServer)/psdscpullserver.svc"
		}
		ResourceRepositoryWeb Resources
		{
			ServerURL = "https://$($DscPullServer)/psdscpullserver.svc"
		}
		ReportServerWeb Reports
		{
			ServerURL = "https://$($DscPullServer)/psdscpullserver.svc"
		}
	}
}

PullClientV2 -NodeGUID $Guid -Output 'C:\DSC\PullClientV2'
Set-DscLocalConfigurationManager -ComputerName 'Localhost' -Path 'C:\DSC\PullClientV2' -Verbose -Force

**Comment by jym972** [comment] 2016-04-20 15:19
Same config for server and client here above except:

**Node with ConfigurationID = xxxx without RegistrationKey = xxxx**
WIN-BABJSO5643U a5fcf0a7-0709-11e6-80c4-00155d013228 Consistency   20/04/2016 17:07:52 30/12/1899 00:00:00 ["{\"IPV4Addresses\":[\"10.10.11.101\",\"127.0.0.1\"],\"CurrentChecksum\":\"8F690215FA9679B4B3A8F4A3C5D7C70E9E368C5126C367A1A5C4687CF477123B\",\"MACAddresses\":[\"00-15-5D-01-32-28\",\"00-00-00-00-00-00-00-E0\"],\"Type\":\"Consistency\",\"HostName\":\"WIN-BABJSO5643U\",\"Locale\":\"fr-FR\",\"StartDate\":\"2016-04-20T17:07:52.9790000+02:00\",\"JobID\":\"{A5FCF0A7-0709-11E6-80C4-00155D013228}\",\"LCMVersion\":\"2.0\",\"IPV6Addresses\":[\"fe80::e521:4830:be5:c43f%14\",\"::2000:0:0:0\",\"::1\",\"::2000:0:0:0\"]}"] [] False 10.10.11.101;127.0.0.1;fe80::e521:4830:be5:c43f%14;::2000:0:0:0;::1;::2000:0:0:0 1135f676-40f7-4cd0-b8e0-00155D013228 

**Node without ConfigurationID = xxxx with RegistrationKey = xxxx**
WIN-E89T1RDB0VN d90a657b-0709-11e6-80bd-00155d013229 Consistency **Pull **20/04/2016 17:09:16 20/04/2016 17:09:18 ["{\"StartDate\":\"2016-04-20T17:09:16.8970000+02:00\",\"IPV6Addresses\":[\"fe80::e54f:3470:a625:94cf%12\",\"::2000:0:0:0\",\"::1\",\"::2000:0:0:0\"],\"DurationInSeconds\":\"2\",\"JobID\":\"{D90A657B-0709-11E6-80BD-00155D013229}\",\"CurrentChecksum\":\"384492764C4AB70C4A5979727BBE20B1C929CAB873A6D0E83BE54E6C10C02409\",\"MetaData\":\"Author: Administrator; Name: myConfiguration01; Version: 2.0.0; GenerationDate: 04/20/2016 01:58:28; GenerationHost: WIN-E89T1RDB0VN;\",\"RebootRequested\":\"False\",\"Status\":\"Success\",\"IPV4Addresses\":[\"10.10.11.100\",\"127.0.0.1\"],\"LCMVersion\":\"2.0\",\"NumberOfResources\":\"2\",\"Type\":\"Consistency\",\"HostName\":\"WIN-E89T1RDB0VN\",\"ResourcesInDesiredState\":[{\"SourceInfo\":\"::10::9::File\",\"ModuleName\":\"PSDesiredStateConfiguration\",\"DurationInSeconds\":\"0,016\",\"InstanceName\":\"HelloWorld\",\"StartDate\":\"2016-04-20T17:09:18.6460000+02:00\",\"ResourceName\":\"File\",\"ModuleVersion\":\"1.1\",\"RebootRequested\":\"False\",\"ResourceId\":\"[File]HelloWorld\",\"ConfigurationName\":\"myConfiguration01\",\"InDesiredState\":\"True\"},{\"SourceInfo\":\"::14::1::WindowsFeature\",\"ModuleName\":\"PsDesiredStateConfiguration\",\"DurationInSeconds\":\"0,875\",\"InstanceName\":\"TelnetClient\",\"StartDate\":\"2016-04-20T17:09:18.6460000+02:00\",\"ResourceName\":\"WindowsFeature\",\"ModuleVersion\":\"1.1\",\"RebootRequested\":\"False\",\"ResourceId\":\"[WindowsFeature]TelnetClient\",\"ConfigurationName\":\"myConfiguration01\",\"InDesiredState\":\"True\"}],\"MACAddresses\":[\"00-15-5D-01-32-29\",\"00-00-00-00-00-00-00-E0\"],\"MetaConfiguration\":{\"AgentId\":\"AB73D03B-00C9-11E6-80B9-00155D013229\",\"ConfigurationDownloadManagers\":[{\"RegistrationKey\":\"\",\"ServerURL\":\"https://DscPullServer.mydsc.local/psdscpullserver.svc\",\"ResourceId\":\"[ConfigurationRepositoryWeb]Configurations\",\"SourceInfo\":\"::17::1::ConfigurationRepositoryWeb\"}],\"ActionAfterReboot\":\"ContinueConfiguration\",\"LCMCompatibleVersions\":[\"1.0\",\"2.0\"],\"LCMState\":\"Idle\",\"ResourceModuleManagers\":[{\"RegistrationKey\":\"\",\"ServerURL\":\"https://DscPullServer.mydsc.local/psdscpullserver.svc\",\"ResourceId\":\"[ResourceRepositoryWeb]Resources\",\"SourceInfo\":\"::22::1::ResourceRepositoryWeb\"}],\"ReportManagers\":[{\"RegistrationKey\":\"\",\"ServerURL\":\"https://DscPullServer.mydsc.local/psdscpullserver.svc\",\"ResourceId\":\"[ReportServerWeb]Reports\",\"SourceInfo\":\"::27::1::ReportServerWeb\"}],\"StatusRetentionTimeInDays\":\"10\",\"LCMVersion\":\"2.0\",\"ConfigurationMode\":\"ApplyAndAutoCorrect\",\"RefreshFrequencyMins\":\"30\",\"RebootNodeIfNeeded\":\"True\",\"RefreshMode\":\"Pull\",\"DebugMode\":[\"NONE\"],\"LCMStateDetail\":\"\",\"AllowModuleOverwrite\":\"True\",\"ConfigurationModeFrequencyMins\":\"15\"},\"Locale\":\"fr-FR\",\"Mode\":\"Pull\"}"]

**Comment by NarineM** [comment] 2016-05-10 21:33
@jym972 
Some fields such as ResourcesInDesiredState are missing in StatusData field when you switch from Registration protocol to use ConfigurationID.  This issue is a product bug and it is being fixed. Since it is not a DSC resource bug but it is reported for xPSDesiredStateConfiguration module I will be closing the issue .

**Comment by NarineM** [comment] 2016-05-10 21:40
@jym972 
Can you file a DSC user voice issue here https://windowsserver.uservoice.com/forums/301869-powershell

and have the user voice link in GitHub here for tracking purposes in case someone else encounters the same issue?

**Comment by jym972** [comment] 2016-05-10 22:08
ok, thanks

**Comment by gigi81** [comment] 2016-05-11 11:00
Hi @NarineM,
What is the status with this issue with ConfigurationId?
I'm still getting bad request events in the event log and this partial status reports as described above.
If it's not a bug in the xPSDesiredStateConfiguration module, what is the product affected by the bug then? To which team we should report this? Is there any change we can have this fixed soon?
Thanks for your help
Luigi

**Comment by NarineM** [comment] 2016-05-11 17:55
@gigi81 
The issue with reporting data not containing certain fields such as ResourcesInDesiredState along with the ETW bad request events is being fixed. The bug is in WMF DSC. You can report a DSC user voice issue here https://windowsserver.uservoice.com/forums/301869-powershell

**Comment by gigi81** [comment] 2016-05-11 22:06
Hi @NarineM 
This is great news! Do you know if the fix is going to be released with a windows update? Thanks

**Comment by Zuldan** [comment] 2016-05-11 22:09
@gigi81, my guess is that it will come with WMF 5.1

**Comment by gigi81** [comment] 2016-05-11 22:11
@Zuldan WMF 5.1 is going to be released along with windows 2016 right? And it doesn't have a released date yet. Do you think we will have to wait that much?

**Comment by Zuldan** [comment] 2016-05-11 22:18
@gigi81, Microsoft is all about continuous delivery these days. I'll be surprised if 5.1 will be tied to a release of a particular OS version. Also, Keep in mind Windows 10 is the client for Windows 2016 (I'm talking same kernel) so there is no reason not release 5.1 before 2016 arrives.

**Comment by gigi81** [comment] 2016-05-11 22:20
@Zuldan ,
I quote: "When Windows Server 2016 ships we will release WMF 5.1"
from this page:
https://blogs.msdn.microsoft.com/powershell/2016/04/06/windows-management-framework-5-0-updates-and-wmf-5-1/

**Comment by theonlyway** [comment] 2016-05-11 23:33
You shouldn't have to wait that long. Had a PFE in last week and he basically said the way Microsoft naming works is they only have the first half of this year to get 2016 out otherwise they are going to have to name it 2017.

**Comment by Zuldan** [comment] 2016-05-12 00:22
@gigi81, I hope that article is incorrect.

**Comment by theonlyway** [comment] 2016-05-12 04:58
I would probably say it is correct. Going off what a Azure PFE told me last week when I queried him about when 2016 was due (Since it's in TP4) to be released he did say it would have to be before the 1st of July because otherwise they would need to call it Server 2017 instead of 2016.

Granted a WMF update would generally come after the release so hopefully 1-3 more months.

**Closed** 2016-08-18 23:10 UTC
Labels: bug, external

**Comment by gigi81** [comment] 2016-12-14 10:37
I guess it's more 6/7 months! But hopefully it's almost here.
https://blogs.msdn.microsoft.com/powershell/2016/12/06/wmf-5-1-releasing-january-2017/

Did anyone tried the WMF 5.1 preview?

**Comment by Zuldan** [comment] 2016-12-14 10:43
I'm pleased to say reporting using ConfigurationID in 5.1 is working perfectly. January can't come soon enough ;-)
