### ISSUE TITLE
xGroup fails with error Server names cannot contain a space character”

### ISSUE THREAD

**Issue by cyruszhang** [PowerShell/xPSDesiredStateConfiguration#287] opened 2016-12-03 19:29 UTC
similar issue here:
https://github.com/PowerShell/xPSDesiredStateConfiguration/issues/180

**Comment by kwirkykat** [comment] 2017-01-19 19:35
Closing this as a duplicate of #288

**Closed by kwirkykat** 2017-01-19 19:35 UTC
Labels: duplicate
